apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: diab_nexus   
        imagePullPolicy: Always
        name: nexus                
        ports:
        - containerPort: 8081