apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: diab_nexus   
        imagePullPolicy: Always
        name: nexus
        volumeMounts:
         - mountPath: /nexus-data
           name: nexusdata                   
        ports:
        - containerPort: 8081
      volumes:
        - name: nexusdata
          hostPath:
            path: /Users/mitchconner/docker/volumes/nexus4kubes/nexus-data
            type: DirectoryOrCreate 