apiVersion: apps/v1
kind: Deployment
metadata:
  name: die-roll-db-deployment
  namespace: {{ .Values.dierolldb.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: die-roll-db
      release: v1
  template:
    metadata:
      labels:
        app: die-roll-db
        release: v1
    spec:
      containers:
      - image: {{ .Values.dierolldb.image }}
        imagePullPolicy: Always
        name: die-roll-db
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: dieroll
          - name: POSTGRES_USER
            value: sketch
          - name: POSTGRES_PASSWORD
            value: passord