apiVersion: v1
kind: Service
metadata:
  name: die-roll-db
  namespace: dieroll
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: NodePort
  selector:
    app: die-roll-db
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost