apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: {{ .Values.namespaces.jenkins_namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: deploy-jenkins
spec:
  tls:
  - hosts:
    - {{ .Values.namespaces.jenkins_namespace }}.localhost
    secretName: tls-secret
  rules:
  - host: {{ .Values.namespaces.jenkins_namespace }}.localhost
    http:
      paths:
        - path: /(/|$)(.*)
          backend:
            serviceName: jenkins
            servicePort: 80
        - path: /([ ]*)(.*)
          backend:
            serviceName: jenkins
            servicePort: 80