apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: deploy-jenkins
spec:
  rules:
  - host: {{ .Values.jenkins.namespace }}.local
    http:
      paths:
        - path: /([ ]*)(.*)
          backend:
            serviceName: jenkins
            servicePort: 80
