apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
spec:
  limits:
  - max:
      memory: 60Mi
      cpu: 100m
    type: Container