apiVersion: v1
kind: LimitRange
metadata:
  name: nexus
  namespace: {{ .Values.nexus.namespace }}
  labels:
    app.kubernetes.io/name: nexus
    app.kubernetes.io/part-of: nexus
spec:
  limits:
  - max:
      memory: 250Mi
      cpu: 150m
    type: Container