apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: {{ .Values.nexus.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
      release: v1
  template:
    metadata:
      labels:
        app: nexus
        release: v1
    spec:
      containers:
      - image: {{ .Values.nexus.image }}  
        imagePullPolicy: Always
        name: nexus                 
        ports:
        - containerPort: 8081