apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: {{ .Values.nexus.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: {{ .Values.nexus.image }}  
        imagePullPolicy: Always
        name: nexus                 
        ports:
        - containerPort: 8081