apiVersion: v1
kind: Service
metadata:
  name: nexus-repo
  namespace: {{ .Values.nexus.namespace }}
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: NodePort
  selector:
    app: nexus
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost