apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: {{ .Values.nexus.namespace }}
spec:
  ports:
    - port: 9081
      targetPort: 8081
      protocol: TCP   
  type: NodePort
  selector:
    app: nexus
