apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: nexus
    release: v1