apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  ports:
    - port: 9081
      targetPort: 8081
      protocol: TCP   
  type: NodePort
  selector:
    app: nexus
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost