apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
  labels:
    app: nexus
spec:
  tls:
  - hosts:
    - nexus.localhost
    secretName: tls-secret
  rules:
  - host: nexus.localhost
    http:
      paths:
        - path: /(/|$)(.*)
          backend:
            serviceName: nexus
            servicePort: 80
        - path: /([ ]*)(.*)
          backend:
            serviceName: nexus
            servicePort: 80