apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: sonarqube
spec:
  tls:
  - hosts:
    - sonarqube.localhost
    secretName: tls-secret
  rules:
  - host: sonarqube.localhost
    http:
      paths:
        - path: /(/|$)(.*)
          backend:
            serviceName: sonarqube
            servicePort: 9000
        - path: /([ ]*)(.*)
          backend:
            serviceName: sonarqube
            servicePort: 9000