apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: deploy-jenkins
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost