apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
  labels:
    app: deploy-jenkins
    release: v1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: deploy-jenkins
      release: v1
  template:
    metadata:
      labels:
        app: deploy-jenkins
        release: v1
    spec:
      containers:
      - image: {{ .Values.jenkins.image }}
        imagePullPolicy: Always
        name: deploy-jenkins
        ports:
        - containerPort: 8080