FROM karlhendrik/jenkins-arm:2.222.1

USER root

RUN sudo apt update 
RUN sudo apt install snapd
RUN sudo snap install kubectl --classic

RUN sudo apt-get install docker-ce docker-ce-cli containerd.io

COPY linux-amd64/helm /usr/local/bin/helm

COPY config /var/jenkins_home/.kube/config