FROM djdefi/rpi-jenkins

COPY configs/plugins.txt /usr/local/jenkins/

COPY install-plugins.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/install-plugins.sh

COPY jenkins-support /usr/local/bin/
RUN chmod 777 /usr/local/bin/jenkins-support

RUN /usr/local/bin/install-plugins.sh < /usr/local/jenkins/plugins.txt


COPY secrets/ /usr/local/jenkins/secrets/
COPY configs/* /usr/local/jenkins/

COPY jobs/ /usr/local/jenkins/jobs/

