FROM djdefi/rpi-jenkins

COPY jobs/ /usr/share/jenkins/ref/jobs/
COPY secrets/ /usr/share/jenkins/ref/secrets/
COPY configs/* /usr/share/jenkins/ref/

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt