# Default values for matts jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  appVersion: "1.0"
  nexus_namespace: nexus

jenkins:
  namespace: jenkins
  # This image will preload jobs, plugins, plugin configs, and credentials. 
  # At some point you will probably want to switch to the :halfbaked tag otherwise 
  # it will attempt to redeploy those items everytime the container restarts
  image: housems/diab_jenkins:fullybaked
  volumes:
    path: /var/lib/docker/volumes/diab_jenkins/_data
    type: DirectoryOrCreate